config/routes.rb
Rails.application.routes.draw do
 
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  devise_for :users,  controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'

  }
  #resources :users

  root to: 'eto#index'
  #root to: 'eto#index'
  #root to: 'page#index'
  get 'about/about'
  get 'about/example'



  #get 'page/contornos', :defaults => { :format => 'json' }
  #get 'page/geojson', :defaults => { :format => 'json' }
  #post 'first/save'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

	# Assuming country_select is used with User attribute `country_code`
	  # This will attempt to translate the country name and use the default
	  # (usually English) name if no translation is available
	  def country_name
	    country = ISO3166::Country[country_code]
	    country.translations[I18n.locale.to_s] || country.name
	  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/eto_controller.rb
class EtoController < ApplicationController
  before_action :authenticate_user!

  def index
  	
  end

  def search
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end
  
  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :country, :city, :area])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create, :destroy]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
     super
  end

  # DELETE /resource/sign_out
   def destroy
     super
   end


  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
   devise_parameter_sanitizer.permit(:sign_in, keys: [:name, :country, :city, :area])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/about/about.html.erb
<div class="container">
  <h2>Acerca de la Plataforma</h2>
  <br>
  <p style="text-align: justify"> Esta plataforma está creada para facilitar al usuario la visualización y búsqueda de información sobre variables de interés. En esta oportunidad, se muestran las variables evapotranspiración y precipitación, teniendo en cuenta que en un  futuro es posible incorporar  una mayor cantidad de variables y datos en general.
    En esta versión se utilizaron datos CHIRPS (Climate Hazards Group InfraRed Precipitation with Station data) que entrega imágenes satelitales incluyendo datos de pluviómetros in situ para crear series temporales grilladas de precipitaciones, especialmente diseñadas para el análisis de tendencias y monitoreo estacional de sequías.
    Evapotranspiracion potencial (PET), aquel obtenido con la grilla CR2MET (periodo 1979-2016) y calculado con método Heargreaves y con resolución de 5 km, diaria. En la siguiente Tabla puedes encontrar mas información:</p>

   <table class="table">
    <thead class="thead-dark">
      <tr>
      	<th scope="col"></th>
        <th scope="col">CHIRPS</th>
        <th scope="col">HEARGREAVES</th> 
      </tr>
      <tr>
        <td>Variable [mm]</td>
        <td>precipitación</td>
        <td>evapotranspiración</td>
      </tr>
      <tr>
        <td>Latitude mínima [°]</td>
        <td>-50</td> 
        <td>-56</td>
      </tr>
      <tr>
        <td>Latitud máxima [°]</td>
        <td>-17.5</td> 
        <td>-17.5</td>
      </tr>
      <tr>
        <td>Longitude mínima [°]</td>
        <td>-75.7</td> 
        <td>-75.8</td>
      </tr>
      <tr>
        <td>Longitud máxima [°]</td>
        <td>-66.4</td> 
        <td>-66.5</td>
      </tr>
      <tr>
        <td>Resolución espacial [°]</td>
        <td>0.25</td>
        <td>0.05</td>
      </tr>
      <tr>
        <td>Resolución temporal</td>
        <td>mensual</td>
        <td>diaria</td>
      </tr>
      <tr>
        <td>Período disponible</td>
        <td>1981-2016</td>
        <td>1979-2016</td>
      </tr>
    </thead>
  </table>

</div>

app/views/about/example.html.erb
<div class="container">
	<h2>Ejemplos de uso</h2>
	<br>
	<ul>
		<li><h5>Generar un mapa de contornos</h5></li>
		<p>Selecciona la variable que quieres ver sobre el mapa y la fecha, en este caso, para precipitación se tienen 
		datos mensuales, y para evapotranspiración datos diarios. Si tienes dudas con respecto al espacio temporal disponible,
		puedes localizar tu mouse sobre el signo de pregunta, este icono te entregará la información necesaria. </p>
		<%= image_tag("map.png",  size: "1200x100", :alt => "mapa evapotranspiración",  :class =>"img-fluid") %>
	</ul>
	<br>
	<ul>
		<li><h5>Descargar el mapa en formato geojson</h5></li>
		<p>Puedes descargar los contornos del mapa utilizando el botón descargar. Se debe iniciar la descarga automáticamente,
		puedes visualizar este tipo de archivos con algún software, como Qgis u otro. En esta versión sólo se puede descargar
		en este formato, en un futuro se pretende agregar más opciones de descarga. </p>
		<%= image_tag("download-chrome.png",  size: "1200x100", :alt => "descargar mapa usando chrome",  :class =>"img-fluid") %>
	</ul>
	<br>
	<ul>
		<li><h5>¿Problemas para descargar el mapa?</h5></li>
		<p> Si no puedes descargar el archivo usando Chrome, utiliza Mozilla Firefox para descargar archivos más pesados.
		Esto ocurre debido a la cantidad de datos y el tamaño del archivo. En Mozilla Firefox, se abrirá una ventana
		como se muestra en la imagen.</p>
		<%= image_tag("download-firefox.png",  size: "1200x100", :alt => "descargar mapa usando firefox",  :class =>"img-fluid") %>
	</ul>
	<br>
	<ul>
		<li><h5>Crear un gráfico temporal de un punto específico </h5></li>
		<p>Esta opción esta disponible, solo para datos mensuales, y limitado sobre un año específico.
		Por lo tanto, puedes obtener datos mensuales de un año. En una próxima versión se espera poder obtener una serie temporal no acotada. </p>
		<%= image_tag("chart.png",  size: "1200x100", :alt => "gráfico de precipitación sobre una coordenada",  :class =>"img-fluid")%>
	</ul>
	<br>
	<ul>
		<li><h5>Descargar como imagen el gráfico </h5></li>
		<p>Esta serie temporal se puede copiar los datos en una tabla excel, o descargar el gráfico como una imagen en formato png. Solo debes registrarte en <a href="https://plot.ly/online-chart-maker/">Ploty Chart Studio</a> y puedes ingresar de forma gratuita.</p>
		<%= image_tag("download-ploty.png",  size: "1200x100", :alt => "uso de ploty",  :class =>"img-fluid")%>
	</ul>
</div>

app/views/eto/index.html.erb
<div class="container_v">
 	<div class="page_body container_h">
		<div class="menu">
      <div class="config">
        <div class= "row">
        	<div class="col-12">
        		<div class="pickerlabel_title"> VARIABLES
              <div class="tool-tip">
              <span class="tool-tip__icon_1" title="Variables disponibles">?</span>
            
          		</div>
            </div>
        	</div>
          <div class="col-12">
            <label class="pickerlabel"> Selecciona la variable </label>
            <div class="btn-group btn-block margin-div">
            	<button id="pr" type="button" class="btn btn-outline-info button_size width-button">PRECIPITACIÓN</button>
            	<button id="eto"  type="button" class="btn btn-outline-info active button_size width-button" >EVAPOTRANSPIRACIÓN</button>
           
       
        		</div>

        	</div>
          <div class="col-12">
        		<div class="pickerlabel_title" id="eto_period_map" > PERIODO
                  <div class="tool-tip">
                  <span class="tool-tip__icon_1" title="Selecciona ĺa fecha que deseas ver dd%mm%aaaa%  1980">?</span>
                
              	</div>
          	</div>
            <div class="pickerlabel_title" id="pr_period_map"> PERIODO
                  <div class="tool-tip">
                  <span class="tool-tip__icon_1" title="Selecciona ĺa fecha que deseas ver dd%mm%aaaa% desde 1981 a 2016 ">?</span>
                
                </div>
            </div>

      		</div>
        	<div class="col-12" >
               
            <div class="pickerlabel" id="eto_date"> Ingresa la fecha del archivo a visualizar
              
                
              <div class="btn-group btn-block margin-div">
              	<table class="width-table">
              		<tbody class="width-table">
              			
                  	<form accept-charset="UTF-8" action="/first/save" method="post">
                  		<tr>
                				<td><label for="day-eto" class="pickerlabel"> día </label></td>
                				<td><label for="month-eto" class="pickerlabel"> mes </label></td>
                				<td><label for="year-eto" class="pickerlabel"> año </label></td>
                    		
                    	</tr>
                    	<tr>
				 								<td><input size="2" name="" id= "day-eto" value=<%="01"%> class="input-day-month"></td>
                    		<td><input type="2" name="" id="month-eto" value=<%="01"%> class="input-day-month"></td>
                    		<td><input type="4" name="" id="year-eto" value=<%="1980"%> class="input-year"></td>
			
                      </tr>
                    </form>
                  
                	</tbody>
                </table>                   	 
        			</div>
            </div>
                 	
            <div class="pickerlabel" id="pr_date"> Ingresa la fecha del archivo a visualizar
             
      	
              <div class="btn-group btn-block margin-div">
              	<table class="width-table">
              		<tbody class="width-table">
              			
                  	<form accept-charset="UTF-8" action="/first/save" method="post">
                  		<tr>
                				
                				<td><label for="month-pr" class="pickerlabel"> mes </label></td>
                				<td><label for="year-pr" class="pickerlabel"> año </label></td>
                    		
                    	</tr>
                    	<tr>

                    		<td><input type="2" name="" id="month-pr" value=<%="01"%> class="input-day-month"></td>
                    		<td><input type="4" name="" id="year-pr" value=<%="1981"%> class="input-year"></td>
			
                      </tr>
                    </form>
                  
                	</tbody>
               	</table>
          		</div>
            </div>

            <div class="row">
              <div class="col-12">
                  
                <div class="btn-group btn-block margin-div">
                	<div class="btn-group btn-block margin-div">
                      	<button id="restart" type="button" class="btn btn-outline-info button_size width-button-small" >CARGAR</button>
                      	                             
                 
           				</div>
            		</div>
              </div>
            </div>
            <div class="row">
          		<div class="col-12">
            		<div class="pickerlabel_title "> DESCARGA EL ARCHIVO
                  <div class="tool-tip">
                  <span class="tool-tip__icon_1" title="Si tienes problemas para descargar prueba con otro navegador como Mozilla Firefox">?</span>
                
                  </div>
                </div>
            	</div>
              <div class="col-12">
                <label class="pickerlabel"> Descargar como geojson </label>
                <div class="btn-group btn-block margin-div">
                  	<button id="geojson" type="button" class="btn btn-outline-info button_size width-button-small">DOWNLOAD</button>
               
            		</div>
          		</div>

            </div>
          </div>

        </div>
      
    		<div class="pickerlabel_title" id="eto_period_chart"> PERIODO A GRAFICAR
              <div class="tool-tip">
              <span class="tool-tip__icon_1" title="Selecciona ĺa fecha que deseas ver dd%mm%aaaa% 1980">?</span>
            
          	</div>
      	</div>
        <div class="pickerlabel_title" id="pr_period_chart"> PERIODO A GRAFICAR
              <div class="tool-tip">
              <span class="tool-tip__icon_1" title="Selecciona ĺa fecha que deseas ver dd%mm%aaaa% desde 1981 a 1982">?</span>
            
            </div>
        </div>

    		
      
               
        <div class="pickerlabel" id="eto_date_start"> Fecha de inicio
          
    	
            
          <div class="btn-group btn-block margin-div">
          	<table class="width-table">
          		<tbody class="width-table">
          			
              	<form accept-charset="UTF-8" action="/first/save" method="post">
              		<tr>
            				<td><label for="day-eto-start" class="pickerlabel"> día </label></td>
            				<td><label for="month-eto-start" class="pickerlabel"> mes </label></td>
            				<td><label for="year-eto-start" class="pickerlabel"> año </label></td>
                		
                	</tr>
                	<tr>
		 								<td><input size="2" name="" id= "day-eto-start" value=<%="01"%> class="input-day-month;"></td>
                		<td><input type="2" name="" id="month-eto-start" value=<%="01"%> class="input-day-month"></td>
                		<td><input type="4" name="" id="year-eto-start" value=<%="1980"%> class="input-year"></td>
	
                  </tr>
                </form>
              
            	</tbody>
            </table>                   	 
    			</div>
        </div>
               	
        <div class="pickerlabel" id="eto_date_end"> Fecha de termino
          
    	
            
          <div class="btn-group btn-block margin-div">
          	<table class="width-table">
          		<tbody class="width-table">
          			
              	<form accept-charset="UTF-8" action="/first/save" method="post">
              		<tr>
            				<td><label for="day-eto-end" class="pickerlabel"> día </label></td>
            				<td><label for="month-eto-end" class="pickerlabel"> mes </label></td>
            				<td><label for="year-eto-end" class="pickerlabel"> año </label></td>
                		
                	</tr>
                	<tr>
		 								<td><input size="2" name="" id= "day-eto-end" value=<%="01"%> class="input-day-month"></td>
                		<td><input type="2" name="" id="month-eto-end" value=<%="01"%> class="input-day-month"></td>
                		<td><input type="4" name="" id="year-eto-end" value=<%="1980"%> class="input-year"></td>
	
                  </tr>
                </form>
              
            	</tbody>
            </table>                   	 
    			</div>
        </div>
                       
        <div class="pickerlabel" id="pr_date_start"> Fecha de inicio
          
  	
          <div class="btn-group btn-block margin-div">
          	<table class="width-table">
          		<tbody class="width-table">
          			
              	<form accept-charset="UTF-8" action="/first/save" method="post">
              		<tr>
            				
            				<td><label for="month-pr-start" class="pickerlabel"> mes </label></td>
            				<td><label for="year-pr-start" class="pickerlabel"> año </label></td>
                		
                	</tr>
                	<tr>

                		<td><input type="2" name="" id="month-pr-start" value=<%="01"%> class="input-day-month"></td>
                		<td><input type="4" name="" id="year-pr-start" value=<%="1981"%> class="input-year"></td>
	
                  </tr>
                </form>
              
            	</tbody>
           	</table>
      		</div>
        </div>
             	
        <div class="pickerlabel" id="pr_date_end"> Fecha de termino
          
  	
          <div class="btn-group btn-block margin-div">
          	<table class="width-table">
          		<tbody class="width-table">
          			
              	<form accept-charset="UTF-8" action="/first/save" method="post">
              		<tr>
            				
            				<td><label for="month-pr-end" class="pickerlabel"> mes </label></td>
            				<td><label for="year-pr-end" class="pickerlabel"> año </label></td>
                		
                	</tr>
                	<tr>

                		<td><input type="2" name="" id="month-pr-end" value=<%="01"%> class="input-day-month"></td>
                		<td><input type="4" name="" id="year-pr-end" value=<%="1981"%> class="input-year"></td>
	
                  </tr>
                </form>
              
            	</tbody>
           	</table>
      		</div>
        </div>
        <div class = "row">
          <div class="col-12">
           <div class="pickerlabel_title"> COORDENADAS
              <div class="tool-tip">
              <span class="tool-tip__icon_1" title="Ingresa las coordenadas manualmente o puedes interactuar con el mapa haciendo click">?</span>
            
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-4">
              
            <label for="latInput" class="pickerlabel">Latitude</label>
          </div>
          <div class="col-8">
            <input id="latInput"/>
          </div>
        </div>
          
        <div class = "row">
          <div class="col-4">
              
            <label for="lngInput"  class="pickerlabel" >Longitude</label>
          </div>
          <div class="col-8">  
            <input id="lngInput" />
          </div>
        </div>
       
        <div class="row">
          <div class="col-12">
              
            <div class="btn-group btn-block margin-div">
            	<div class="btn-group btn-block margin-div">
                  	<button id="average" type="button" class="btn btn-outline-info button_size width-button-small" >GRAFICAR PROMEDIO</button>
                  	                             
             
       				</div>
        		</div>
          </div>
        </div>
        



        <br>
      </div>
    </div>
    <div id="map" >
  
			
		</div>   
  
  </div>
 </div>

 <div class="style-char-div">
 	
  <div id="chart" >
  
      
  </div>
 </div>

 <h6 class="margin-copyright">autor: nvaldebenito</h6>
 <%= image_tag("copyright.jpg") %>
 

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark" style="background-color: #e3f2fd;">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if user_signed_in? %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a class="navbar-brand" href="<%= edit_user_registration_path %>"><%= current_user.name %><span class="sr-only navbar-brand"></span></a>
          </li>
          <li  class="nav-item">
            <a href="<%= destroy_user_session_path %>" class="navbar-brand" data-method="DELETE">Log out<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a href="<%= about_about_path %>" class="navbar-brand"> Acerca de la plataforma </a>
          </li>
          <li class="nav-item">
            <a href="<%= about_example_path %>" class="navbar-brand"> Ejemplos de uso </a>
          </li>
          <li class="nav-item">
            <a href="<%= root_path %>" class="navbar-brand"> Ir a la plataforma </a>
          </li>
                        
        </ul>
      </div><!-- /.navbar-collapse -->
    <% else %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">  
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <a href="<%= user_session_path %>" class="navbar-brand" data-method="POST">Log in<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a href="<%= about_about_path %>" class="navbar-brand"> Acerca de la plataforma </a>
          </li>
          <li class="nav-item">
            <a href="<%= about_example_path %>" class="navbar-brand"> Ejemplos de uso </a>
          </li>
  
        </ul>
      </div>
    <% end %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <br>
      <h1 style="font-size: 24px; text-align: left; "> <%= image_tag("cr2.png", :alt => "Logo Plataforma de visualización cr2") %>
       PLATAFORMA DE VISUALIZACIÓN</h1>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cr2mmaDev</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js' %>
    <%= javascript_include_tag "https://api.tiles.mapbox.com/mapbox.js/v2.2.4/mapbox.js" %>
    <%= stylesheet_link_tag "https://api.tiles.mapbox.com/mapbox.js/v2.2.4/mapbox.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- CSS -->

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script type='text/javascript' src='//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js'></script>
    <script type='text/javascript' src='http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js'></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://unpkg.com/leaflet@1.0.3/dist/leaflet.js"></script>
    

  </head>
  <body">
    <%= render 'layouts/navbar' %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_chart.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<%= javascript_include_tag "active_admin", "chartkick" %>


<% my_chart = User.group_by_day(:created_at).count %>
<%= area_chart my_chart %>

<%= geo_chart User.group(:country).count %>

<% 	my_chart = User.group(:city).count %>
<%= pie_chart my_chart %>
<
<% my_chart = User.group(:country).count %>
<%= pie_chart my_chart %>

app/views/shared/_chart1.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<%= javascript_include_tag "active_admin", "chartkick" %>


<% my_chart = User.group_by_day(:created_at).count %>
<%= area_chart my_chart, download: {filename: "users_registration"}  %>

app/views/shared/_chart2.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<%= javascript_include_tag "active_admin", "chartkick" %>

<% 	my_chart = User.group(:city).count %>
<%= pie_chart my_chart, download: {filename: "coutry_users"}  %>

<% my_chart = User.group(:country).count %>
<%= pie_chart my_chart, download: {filename: "city_users"} %>

app/views/shared/_chart3.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<%= javascript_include_tag "active_admin", "chartkick" %>

<%= geo_chart User.group(:country).count %>

app/views/shared/_chart4.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<%= javascript_include_tag "active_admin", "chartkick" %>


<% my_chart = User.group(:area).count %>
<%= column_chart my_chart, download: {filename: "area_users"}  %>